// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK29YPrJznbUwQd4xTdHijABtf-uc5he4',
    appId: '1:473618040953:web:c87bafd4d0204450f26ca8',
    messagingSenderId: '473618040953',
    projectId: 'babyshophub-55389',
    authDomain: 'babyshophub-55389.firebaseapp.com',
    storageBucket: 'babyshophub-55389.firebasestorage.app',
    measurementId: 'G-DM5X8JP72W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSJ_uJF3Z4XgilZOOMjzVm2dsgJosBE5c',
    appId: '1:473618040953:android:3c84b8d54504c370f26ca8',
    messagingSenderId: '473618040953',
    projectId: 'babyshophub-55389',
    storageBucket: 'babyshophub-55389.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2TQ77zNRP4F-GJq_oSlzlrXVA6JyE5wI',
    appId: '1:473618040953:ios:aa25cf1bf653ebf0f26ca8',
    messagingSenderId: '473618040953',
    projectId: 'babyshophub-55389',
    storageBucket: 'babyshophub-55389.firebasestorage.app',
    iosBundleId: 'com.example.babyshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2TQ77zNRP4F-GJq_oSlzlrXVA6JyE5wI',
    appId: '1:473618040953:ios:aa25cf1bf653ebf0f26ca8',
    messagingSenderId: '473618040953',
    projectId: 'babyshophub-55389',
    storageBucket: 'babyshophub-55389.firebasestorage.app',
    iosBundleId: 'com.example.babyshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK29YPrJznbUwQd4xTdHijABtf-uc5he4',
    appId: '1:473618040953:web:be6431f3ae229455f26ca8',
    messagingSenderId: '473618040953',
    projectId: 'babyshophub-55389',
    authDomain: 'babyshophub-55389.firebaseapp.com',
    storageBucket: 'babyshophub-55389.firebasestorage.app',
    measurementId: 'G-99VPE67BLN',
  );
}
